### ISSUE TITLE
Adicionar Message Broker para comunicação entre os microsserviços

### ISSUE THREAD

**Issue by luksamuk** [luksamuk/minerva-system#34]
A issue #12 precisa que isso seja implementado para que possa ser feita. Para explicar o problema, ela será usada como exemplo.

Ao remover um usuário, seria necessário também remover suas sessões no MongoDB e no Redis, do contrário ele poderá continuar acessando o sistema por no máximo uma semana até que sua sessão expire, ou até que faça logoff.

Isso poderia ser resolvido de forma que `USER` acessasse diretamente o MongoDB e o Redis, mas isso envolveria o uso da biblioteca de cache, o que deve ser evitado para minimizar acomplamento e para ter binários mais inchados -- por mais que isso já seja feito com Mongo e a biblioteca data.

Outra ideia seria realizar uma conexão gRPC entre `USER` e `SESSION`, mas por mais que isso possa ser feito com certa rapidez e confiança, a remoção dessas sessões não deveria ser um fator bloqueante na remoção do usuário. Em outras palavras, se o usuário foi removido com sucesso do PostgreSQL, essa informação deveria retornar imediatamente e a remoção das sessões deveria ser uma tarefa pendente.

Isso é um trabalho para um message broker (como RabbitMQ). Ao realizar a remoção do usuário, deveria ser feito o broadcast dessa mensagem pelo sistema sob um tópico específico e, ao escutar essa mensagem, uma das réplicas de SESSION deveria consumi-la e fazer o que for necessário para remover a sessão, sob esse evento.

#### CI/CD

- [x] Adicionar forma de executar RabbitMQ para desenvolvimento
- [x] Adicionar RabbitMQ no Docker Compose
- [x] Adicionar RabbitMQ no Docker Swarm
- [x] Adicionar cluster RabbitMQ no Kubernetes
  - [x] Adicionar RabbitMQ non-cluster no Kubernetes, para ambientes IoT
- [x] Adicionar RabbitMQ como serviço nos testes unitários

#### Preparação

- [x] Adicionar variáveis de ambiente do RabbitMQ (serviço apenas; porta fixa em 5672)
  - [x] Arquivo `.env`
  - [x] Docker Compose
  - [x] Docker Swarm
  - [x] Kubernetes
- [x] `RUNONCE`: Adicionar criação de elementos padrão do RabbitMQ
  - [x] Criar biblioteca `minerva-broker`
  - [x] `minerva-broker`: Adicionar funcionalidade de criação de tenants (via método PUT na [API REST do RabbitMQ](https://www.rabbitmq.com/vhosts.html))
  - [x] `minerva-broker`: Adicionar funcionalidade de geração de links de conexão
  - [x] `minerva-broker`: Adicionar funcionalidade de geração de conexão com tenant do RabbitMQ
  - [x] Adicionar tenants no RabbitMQ
  - [x] Adicionar filas de mensagens padrão para cada tenant

#### `DISPATCH`

- [x] Adicionar microsserviço
- [x] Consumir mensagens de sessão (despachar remoção de sessões para `SESSION` -- ver #12)
- [x] Refatorar (melhorar separação entre o consumer e as rotinas para cada fila)
- ~Adicionar testes unitários~ (não se aplica)
- [ ] Adicionar testes de integração

#### `USER`

- [x] Ao remover um usuário: Enviar mensagem de remoção de sessão do usuário, daquele tenant em específico (ver #12)

### Documentação

- [x] Regras de negócio de mensageria (quando usar, filas padrão, multi-tenancy, etc)
- [x] Documentação da nova biblioteca `minerva-broker`
- [x] Documentação de deploy k8s para ARM64
- [x] Adicionar documentação de mudanças nas configurações do Kubernetes
  - [x] Refatorar diagrama de estrutura do cluster para diagramas menores
- [x] Adicionar novas documentações de endpoints expostos via Ingress
- [x] Atualizar changelog
- [x] [Documentar MVP para Plan 9](https://git.sr.ht/~luksamuk/minerva9)
- [x] Documentar ferramentas que podem ser usadas para inspecionar serviços _third-party_
  - MongoDB Compass
  - RESP.app
  - DBeaver CE
  - Mencionar uso de port-forward com k8s para tal

### Extras

- [x] Consumir métricas do cluster RabbitMQ no Kubernetes
  - [x] Adicionar serviço Prometheus
    - [x] Ajustar Prometheus para coleta de dados em RabbitMQ non-cluster (adicionar plugin?)
  - [x] Adicionar serviço Grafana
    - [x] Ajustar dashboards do Grafana para uso non-cluster do RabbitMQ
- [x] Realizar [testes de stress com k6](https://k6.io/docs/test-types/stress-testing/)

**Comment by luksamuk** [comment]
O primeiro passo para resolução disso é fazer alguns testes usando Rust e RabbitMQ. Algumas bibliotecas seguem como opção, mas especialmente a [Lapin](https://github.com/luksamuk/amqp-rs/lapin), por suportar async.

**Comment by luksamuk** [comment]
O RabbitMQ possibilita a obtenção de métricas em seu deployment k8s, que podem ser coletadas através do Prometheus para subsequente análise visual no Grafana. Isso foi adicionado por comodidade, e poderá ser explorado no futuro para coletar métricas dos microsserviços também.

**Comment by luksamuk** [comment]
Algumas coisas precisam ser resolvidas ainda.

Primeiramente, é necessário desacoplar um pouco as mensagens de sessão do microsserviço DISPATCH, no sentido de que ele agora só funciona para essa fila. É necessário desde já dar suporte a mais filas, para que possa ser implementado com facilidade.

Em segundo lugar, o serviço DISPATCH não está retornando no Docker Compose porque, numa falha, seu processo retorna 0. Acabo de corrigir isso, mas será necessário testar.

Enfim, será necessário criar a documentação do módulo, documentar a biblioteca `minerva-broker` também, ajustar documentações de `USER` para deixar claro o uso de mensageria, e enfim descrever o uso de tudo isso na documentação, o que inclui diagramas de classes.

No caso do diagrama do Kubernetes, vou avaliar se seria interessante destrinchá-lo em mais diagramas; no caso, um por serviço, e um generalizado que descreve apenas a dinâmica dos `Services` e `Ingresses`.

**Comment by luksamuk** [comment]
O serviço DISPATCH apresentou erros no Kubernetes, especialmente com BackOff, depois de passar dois dias a fio rodando. O erro aparentemente foi ocasionado por um unwrap em um ConnectionError, mais especificamente ao se conectar -- imagino que o serviço tenha morrido por detalhe similar.

![Screenshot_2022-07-14-22-57-35-278_com.termux.jpg](https://user-images.githubusercontent.com/3826977/179131266-8d21b114-8c02-4522-8a8f-ef01795311c9.jpg)

Se bem entendi, isso tem algo a ver com o RabbitMQ fechando conexões. Será problema de deploy?

**Comment by luksamuk** [comment]
Pelo que parece, existe alguma coisa relacionada a deletar as filas por inatividade. Pelos logs do RabbitMQ, a conexão é recusada justamente por isso.

![Screenshot_2022-07-14-23-06-43-612_com.termux.jpg](https://user-images.githubusercontent.com/3826977/179132213-a302d1c3-1ef7-4d3e-94b1-019b3548b4ee.jpg)

Isso pode ser confirmado pelo próprio painel do RabbitMQ:

![Screenshot_2022-07-14-23-08-31-096_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/3826977/179132265-9b5b484e-070e-44ae-8b31-5acaad338943.jpg)

Existem duas opções aqui. A primeira é assegurar a persistência dessas filas; a segunda é que, ao se conectar a uma fila, caso a mesma não exista, que nós a criemos imediatamente.

**Comment by luksamuk** [comment]
De fato foi observado que as filas criadas pelo job `RUNONCE` não estavam configuradas para serem _durable_ por padrão. Isso foi feito, mas ainda demanda testes.

**Comment by luksamuk** [comment]
> De fato foi observado que as filas criadas pelo job `RUNONCE` não estavam configuradas para serem _durable_ por padrão. Isso foi feito, mas ainda demanda testes.

Desde esse comentário mantive o sistema funcionando e pude observar que, mesmo com ociosidade longa, as queues continuam existindo. Acredito que isso está ok, então vou marcar o `RUNONCE` como "done".

Além disso, andei fazendo ajustes para organizar as configurações do k8s, já que possuem muitos arquivos. Unifiquei-os onde podia. Também realizei exposição dos serviços via Ingress através de Traefik (padrão do K3s). Isso coloca a configuração de Ingress do Minerva como dependente de Traefik, o que não lida muito bem com Microk8s e com Minikube, se bem acredito, mas posta a natureza do projeto e agora a montagem da minha infraestrutura local usando K3s (inclusive através de Raspberry Pi), acredito que é algo com que posso me comprometer.

**Comment by luksamuk** [comment]
Removi algumas tags desnecessárias, agora que este trabalho já está praticamente pronto. Alguns ajustes foram feitos para que o RabbitMQ e o MongoDB executassem em ambientes IoT (K3s em Raspberry Pi 4 Model B, mais especificamente). A intenção a seguir é documentar isso, e talvez ajustar alguns dashboards do Grafana para situações em que o RabbitMQ não é executado em cluster. Talvez ajustar a saída desses dados para o Prometheus.

**Comment by luksamuk** [comment]
A única coisa que falta agora são os testes para o módulo DISPATCH.
É provável que seja necessário bolar uma forma inteligente de fazer testes de integração também.

**Comment by luksamuk** [comment]
...não vai ter testes em DISPATCH. Não precisa. E é isso.

**Comment by pedroavo04** [comment]
Olá como criar arquivos sypware
